### PR TITLE
Added dynamic vars for authentication

### PR DESCRIPTION
**Pull request by surudoiryu**

### CODE REVIEW

**Comment by 030** [comment]
Possible fix: set 4.1.1 in  ansible-verdaccio/tests/requirements.yml as ansible_user related issue seems to be fixed in that version

**Comment by 030** [comment]
Please add 

```
  vars:
    nodejs_install_npm_user: root
```
to the test.yml

**Comment by surudoiryu** [comment]
Just saw this post about it
https://github.com/geerlingguy/ansible-role-nodejs/issues/66

**Comment by 030** [comment]
Please release the current `Update apt cache` with the following snippet:

```
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
```

**Review by 030 — APPROVED** [review]

**Pull request merged**
